Repository appliedblockchain/giano, pull requests merged in 2025-07, with the labels that each got.

#38 misc: add connector build step to readme
  README.md
Labels: documentation

#51 support multiple owners and demo page
  packages/connector/src/account/toGianoSmartAccount.ts
  packages/connector/src/index.ts
  packages/contracts/src/GianoSmartWallet.sol
  services/custom-example/.env-local
  services/custom-example/next.config.js
  services/custom-example/script/append-address-env-vars.js
  services/custom-example/src/pages/multiple-owners.tsx
  services/custom-example/src/wagmi.ts
Labels: enhancement

#57 Port Coinbase wallet v1.1.0 changes
  packages/contracts/foundry.toml
  packages/contracts/src/GianoSmartWallet.sol
  packages/contracts/src/GianoSmartWalletFactory.sol
  packages/contracts/test/GianoSmartWallet/ValidateUserOp.t.sol
  packages/contracts/test/GianoSmartWalletFactory.t.sol
  services/custom-example/.env-base-sepolia
  services/custom-example/.env-local
Labels: enhancement

#59 Fix: missing ensureAccountDeployed(..) helper
  packages/connector/src/provider.ts
Labels: bug

#62 Expand credential creation and retrieval
  packages/connector/src/account/get-credential.ts
  packages/connector/src/account/get-web-authn-account.ts
  packages/connector/src/account/index.ts
  packages/connector/src/provider-injection/injection.ts
  packages/connector/src/provider-injection/types/credential-info.ts
  packages/connector/src/provider-injection/types/credential-info/base-credential-info.ts
  packages/connector/src/provider-injection/types/credential-info/credential-info.ts
  packages/connector/src/provider-injection/types/credential-info/credential-mediation-requirement.ts
  packages/connector/src/provider-injection/types/credential-info/defaults.ts
  packages/connector/src/provider-injection/types/credential-info/index.ts
  packages/connector/src/provider-injection/types/credential-info/resident-key-requirement.ts
  packages/connector/src/provider-injection/types/credential-info/user-verification-requirement.ts
  packages/connector/src/provider.ts
Labels: enhancement
